name: Ejecutar Notificador de HackerOne

on:
  schedule:
    - cron: "0 */3 * * *"  # Ejecuta cada 3 horas
  workflow_dispatch:  # Permite ejecuci√≥n manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: üì• Clonar el repositorio
        uses: actions/checkout@v4

      - name: üêç Configurar Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: üì¶ Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: üöÄ Ejecutar script de monitoreo
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python notifier.py #Corremos nuestro bot, el cual se encargara de enviar los correos