name: Ejecutar Notificador de HackerOne

on:
  schedule:
    - cron: "0 */3 * * *"  # Cada 3 horas, por ahora lo veo conveniente. 
  workflow_dispatch:  # EjecuciÃ³n manual

permissions:
  contents: write  # ğŸ” con esto permito push a mi repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Clonar el repositorio
        uses: actions/checkout@v4

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ğŸ“¦ Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: ğŸš€ Ejecutar script de monitoreo
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }} #obvio que no lo voy a poner aqui a texto plano XD
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python notifier.py

      - name: ğŸ”„ Commit y push de latest_program.json al repositorio #mejor asÃ­ me ahorro el bororÃ³ de los Artifacts en Github Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest_program.json
          git diff --cached --quiet || git commit -m "chore: update latest_program.json with new HackerOne program state"
          git push
